下記エラー解消
Digest: sha256:1699c10032ca2582ec89a24a1312d986a3f094aed3d5c1147b19880afe40e052
Status: Downloaded newer image for golang:1.22-alpine
 ---> 4129f51f28c9
Step 2/12 : WORKDIR /app
 ---> Running in df18f24a8ff2
Removing intermediate container df18f24a8ff2
 ---> 094ecc16d896
Step 3/12 : COPY go.mod go.sum ./
 ---> 592c82b5f5b9
Step 4/12 : RUN go mod download
 ---> Running in 7bb88a879130
verifying github.com/lib/pq@v1.10.9/go.mod: checksum mismatch
	downloaded: h1:AlVN5x4E4T544tWzH6hKfbfQvm3HdbOxrmggDNAPY9o=
	go.sum:     h1:Al+/TG5ILrupMYksZnHNW45Hq4nMUCabRefEQNe3ZK8=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'.
The command '/bin/sh -c go mod download' returned a non-zero code: 1
Finished Step #1 - "Build"
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1